// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw-FabIFeaBpedH6-o1GgEOkcvaY6e4TU',
    appId: '1:400315759726:web:d7e9b8ef30828b48e9fa7f',
    messagingSenderId: '400315759726',
    projectId: 'memorymate-38f98',
    authDomain: 'memorymate-38f98.firebaseapp.com',
    storageBucket: 'memorymate-38f98.appspot.com',
    measurementId: 'G-VZZZW9FVR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVGZPVbxpkTVCedEETiC6n8sqWb1EdD9g',
    appId: '1:400315759726:android:d3388ebe0ffb2c28e9fa7f',
    messagingSenderId: '400315759726',
    projectId: 'memorymate-38f98',
    storageBucket: 'memorymate-38f98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlbRRfaKsdrV2l2X7GV8jNrY3dl77LGkU',
    appId: '1:400315759726:ios:9fc1b13dba5e425ee9fa7f',
    messagingSenderId: '400315759726',
    projectId: 'memorymate-38f98',
    storageBucket: 'memorymate-38f98.appspot.com',
    iosBundleId: 'com.example.ver2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlbRRfaKsdrV2l2X7GV8jNrY3dl77LGkU',
    appId: '1:400315759726:ios:9fc1b13dba5e425ee9fa7f',
    messagingSenderId: '400315759726',
    projectId: 'memorymate-38f98',
    storageBucket: 'memorymate-38f98.appspot.com',
    iosBundleId: 'com.example.ver2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw-FabIFeaBpedH6-o1GgEOkcvaY6e4TU',
    appId: '1:400315759726:web:0cc51ae04f720941e9fa7f',
    messagingSenderId: '400315759726',
    projectId: 'memorymate-38f98',
    authDomain: 'memorymate-38f98.firebaseapp.com',
    storageBucket: 'memorymate-38f98.appspot.com',
    measurementId: 'G-HS93D96Y7B',
  );
}
